version: 2

sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
