version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

python:
  install:
    # Install package too, so autodoc works
    - method: pip
      path: .
    - requirements: docs/requirements.txt
